{% set name = "psana" %}
{% set version = "3.3.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/lcls2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0b56923aa9628fce3f7c62cef2ed9df376a9efe0f09d3af48909c8810d8344ed

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
    - psalg
  run:
    - python
    - numpy
    - matplotlib
    - xtcdata
    - psalg
    - requests
    - mpi4py
    - mongodb
    - pymongo
    - amityping
    - mypy_extensions
    - h5py 
    - pyzmq
    - psmon
    - h5py
    - krtc
    - ipykernel 
    - opencv 
    - scikit-learn 
    - pyabel 

about:
  home: https://github.com/slac-lcls/lcls2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'LCLS-II DAQ and Software'
  description: |
    DAQ and analysis software for LCLS-II
  doc_url: https://github.com/slac-lcls/lcls2 
  dev_url: https://github.com/slac-lcls/lcls2

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
