{% set name = "psana" %}
{% set version = "4.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/lcls2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4b703ae6d23426c0c89717260dfad08ab51b7e77bcc8a4eeff9fed1fd90afbec

build:
  skip: True  # [win]
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python=3.12.*
    - setuptools
    - pip
    - numpy=1.26.4
    - cython
    - xtcdata={{ version }}
    - psalg={{ version }}
  run:
    - python=3.12.*
    - numpy=1.26.4
    - matplotlib
    - xtcdata={{ version }}
    - psalg={{ version }}
    - requests
    - openmpi
    - mpi4py
    - h5py
    - pyzmq
    - psmon
    - krtc
    - ipykernel 
    - prometheus_client
    - amityping
    - bson
    - kafka-python-ng
    - scipy

about:
  home: https://github.com/slac-lcls/lcls2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'LCLS-II DAQ and Software'
  description: |
    DAQ and analysis software for LCLS-II
  doc_url: https://github.com/slac-lcls/lcls2 
  dev_url: https://github.com/slac-lcls/lcls2

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
    - melchior
